/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1d6b6fe1f6b93d4933a7b0abad561279)
interface __BaseEnv_Env {
	DB: D1Database;
	TEAM_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEAM_TOKEN">> {}
}
